import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const sourcePath = join(__dirname, "page.js");

test("home page renders current status and latest run detail sections", async () => {
  const source = await readFile(sourcePath, "utf8");
  assert.match(source, /현재 상태/);
  assert.match(source, /운영 콘솔 요약/);
  assert.match(source, /운영 큐/);
  assert.match(source, /승인 사유 요약/);
  assert.match(source, /계획 확인 필요/);
  assert.match(source, /복구 사유 요약/);
  assert.match(source, /재시도 소진/);
  assert.match(source, /승인 대기 상세/);
  assert.match(source, /수동 게이트 사유/);
  assert.match(source, /누적 재시도/);
  assert.match(source, /재개 횟수/);
  assert.match(source, /복구 요약/);
  assert.match(source, /단계 시간 요약/);
  assert.match(source, /세션 건강도/);
  assert.match(source, /복구 필요 신호는 승인 필요 항목과 일부 겹칠 수 있습니다/);
  assert.match(source, /데이터 가용성/);
  assert.match(source, /현재 콘솔이 볼 수 있는 데이터/);
  assert.match(source, /아직 수집하지 않는 데이터/);
  assert.match(source, /단일 executor 기준으로 동작하는 read-only 운영 콘솔/);
  assert.match(source, /queue 적체와 worker 상태는 아직 수집하지 않습니다/);
  assert.match(source, /액션 필요 실행/);
  assert.match(source, /원인 분류/);
  assert.match(source, /다음 액션/);
  assert.match(source, /최근 실행 이력/);
  assert.match(source, /최신 실행 상세/);
  assert.match(source, /단계 타임라인/);
  assert.match(source, /시작 시간/);
  assert.match(source, /종료 시간/);
  assert.match(source, /소요 시간/);
  assert.match(source, /현재 실행은 있지만 최신 활동 시각이 없습니다/);
  assert.match(source, /현재 실행 데이터가 없습니다/);
  assert.match(source, /Asia\/Seoul/);
  assert.match(source, /statusLabel/);
  assert.match(source, /buildOperationsConsoleSummary/);
  assert.match(source, /currentUpdatedAt:\s*current\?\.last_activity_at/);
  assert.match(source, /readCurrentRun/);
  assert.match(source, /listRecentRuns/);
  assert.doesNotMatch(source, /Root:/);
});
